local SETTINGS = {}

SETTINGS.MODULE_NAME = script.Parent.Name

SETTINGS.DEBUG_MODE = true
SETTINGS.VISUALIZE = false

SETTINGS.GENERATE_ANIMATOR = false -- Beta Setting not fully functional
SETTINGS.GENERATE_TEAMS = true
SETTINGS.GENERATE_ATTACK_RADIUS = true


return SETTINGS
